version: '3.1'
services:
        mysql57:
               restart: always
               image: mysql:5.7
               container_name: mysql
               build: /opt/mysql
               ports:
                    - 3306:3306             //端口自定义
               environment:
                       TZ: Asia/Shanghai 
                       MYSQL_ROOT_PASSWORD: mysql       //setting ROOT密码
               command:                                 //配置
                       --lower_case_table_names=1
                       --character-set-server=utf8
                       --collation-server=utf8_unicode_ci
                       --init-connect='SET NAMES utf8'
                       --sql-mode=""
                       --wait_timeout=86400
                       --interactive_timeout=86400
                       --max_connections=300
                       --open_files_limit=8192
                       --max_heap_table_size=671M
                       --tmp_table_size=671M
                       --innodb_buffer_pool_size=1G
                       --innodb_buffer_pool_instances=8
               volumes:                                 //本地目录与容器目录同步
                   - /opt/mysql/date:/var/lib/mysql
                   - /opt/mysql/init:/docker-entrypoint-initdb.d/
